import {
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  ChevronRight,
  ChevronsUpDown,
  Chrome,
  Eye,
  Github,
  GraduationCap,
  Inbox,
  Laptop,
  List,
  Loader2,
  LogOut,
  Moon,
  PenLine,
  Plus,
  PlusCircle,
  Settings,
  ShoppingCart,
  Sun,
  Trash2,
  User2,
  UserCog2,
  X
} from 'lucide-react'

export type { LucideIcon as IconType } from 'lucide-react'

export const Icons = {
  calendar: Calendar,
  calendarDays: CalendarDays,
  check: Check,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  eye: Eye,
  github: Github,
  google: Chrome,
  inbox: Inbox,
  laptop: Laptop,
  list: List,
  logo: CheckCircle,
  logout: LogOut,
  moon: Moon,
  pen: PenLine,
  plus: Plus,
  plusCircle: PlusCircle,
  school: GraduationCap,
  settings: Settings,
  shoppingCart: ShoppingCart,
  spinner: Loader2,
  sun: Sun,
  trash: Trash2,
  user: User2,
  userSettings: UserCog2,
  x: X
}
